name: flutterflow_ui
description: UI components used by FlutterFlow's code generation.
homepage: https://docs.flutterflow.io
repository: https://github.com/FlutterFlow/flutterflow-ui

# google_mobile_ads, flutter_braintree, and chat have been disabled.
# flutter_html, sign_in_with_apple, and assets_audio_player have been added manually.



# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  auto_size_text: any
  cached_network_image: any
  chewie: any
  collection: any
  emoji_flag_converter: any
  fl_chart: any
  flutter_credit_card: any
  flutter_google_places: any
  font_awesome_flutter: any
  google_api_headers:
  google_fonts: any
  google_maps_flutter: any
  google_maps_webservice:
  internet_file: any
  intl: any
  json_path: any
  json_serializable: any
  mapbox_search: any
  mime_type: any
  page_transition: any
  pdfx: any
  rive: any
  rxdart: any
  shared_preferences: any
  table_calendar: any
  timeago: any
  url_launcher: any
  video_player: any
  webviewx: any
  youtube_plyr_iframe: any
  
  # For assets_audio_player
  uuid: any
  http: any
  path_provider: any

  # For flutter_html
  html: any
  csslib: any
  flutter_layout_grid: any
  webview_flutter: any
  chewie_audio: any
  flutter_svg: any
  numerus: any

dev_dependencies:
  dependency_validator:

# For information on the generic Dart part of this file, see the
# following page: any

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

